application: quizcon
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images
- url: /templates
  static_dir: templates
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: quizcon.py

